name: jd_crazy

on:
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: jd_crazy
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lxk0301/jd_scripts
          ref: 'master'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行领京豆'
        run: |
          node jd_crazy_joy.js
          node jd_crazy_joy_coin.js &
          sleep 1m
          ps -ef | grep node | grep -v grep | cut -c 9-15 | xargs kill -s 9
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: jd_crazy
  # test:
  #   runs-on: ubuntu-latest
  #   if: github.event.repository.owner.id == github.event.sender.id
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up Python 3.7
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.7
  #     - name: '运行领京豆'
  #       run: |
  #         pip3 install requests
  #         python3 jd_crazy.py
  #       env:
  #         JD_COOKIE: ${{ secrets.JD_COOKIE }}
  #         JD_DEBUG: ${{ secrets.JD_DEBUG }}
  #         PUSH_KEY: ${{ secrets.PUSH_KEY }}
  #     - name: Repository Dispatch
  #       uses: peter-evans/repository-dispatch@v1
  #       with:
  #         token: ${{ secrets.PAT }}
  #         event-type: jd_crazy